### ISSUE TITLE
Warn the user if registry is found as one of the app and document it

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster-docker-compose#2]
I was trying the below but seems like the registry doesnt have a yml config required. Is it suppose to work? 

cc @pascalgrimaud @PierreBesson @jdubois 

```
Deepu@DESKTOP-3NUQHBI D:\Projects\singsug\ms\docker
> yo jhipster-docker-compose

        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

                            http://jhipster.github.io

Welcome to the JHipster Docker Compose Generator
Files will be generated in folder: D:\Projects\singsug\ms\docker
? Where are the applications located ? ../
4 applications found at D:\Projects\singsug\ms\

? Which applications do you want in your DockerFile ? gatewayApp, jhipster-registry, msapp1, msapp2
? Do you want ELK to monitor your applications ? Yes
? Which profile do you want to use ? dev

Checking Docker images in applications directories...
Found Docker images, writing files...

   create docker-compose.yml
   create registry.yml
   create central-server-config\application.yml
   create elk.yml
   create log-monitoring\log-config\logstash.conf
   create log-monitoring\log-data\.gitignore

##### USAGE #####
Launch all your applications by running : docker-compose up -d


Deepu@DESKTOP-3NUQHBI D:\Projects\singsug\ms\docker
> docker-compose up -d
ERROR: .IOError: [Errno 2] No such file or directory: 'D:\\Projects\\singsug\\ms\\jhipster-registry\\src\\main\\docker\\app.dev.yml'

Deepu@DESKTOP-3NUQHBI D:\Projects\singsug\ms\docker
```

**Comment by deepu105** [comment]
Ok My bad I didnt notice that you are auto configuring registry.

May be we need to update docs to tell the user that registry is included

**Comment by pascalgrimaud** [comment]
Can you show your docker-compose file plz?
Le 15 mars 2016 7:42 AM, "Deepu K Sasidharan" notifications@github.com a
écrit :

**Comment by deepu105** [comment]
@pascalgrimaud I had the jhipster-registry project in the folder as well so the generator was trying treat it like a normal app hence the error.

may be if the app name has registry in it we should warn the user as well

**Comment by pascalgrimaud** [comment]
mhhh I can see a `.yo-rc.json` file in jhipster-registry project.
I don't think it's normal because we can't generate a jhipster-registry from generator-jhipster

**Comment by deepu105** [comment]
yes but our registry repo has a yo-rc file

**Comment by deepu105** [comment]
Btw while running `docker-compose up -d` from the generated docker folder gives me error any idea why?

```
PS D:\Projects\singsug\ms\docker> docker-compose up -d
Creating jhipster-registry
Pulling elk-elasticsearch (elasticsearch:2.2.0)...
2.2.0: Pulling from library/elasticsearch

[0Bd7827f33: Pulling fs layer
[0B95caeb02: Pulling fs layer
[0Bd0fe50cc: Pulling fs layer
[0B1295bce9: Pulling fs layer
[0B6b0e1928: Pulling fs layer
[0Bc6e4eb7c: Pulling fs layer
[0B44e1612b: Pulling fs layer
[0Bd9deb980: Pulling fs layer
[0Ba8a931c3: Pulling fs layer
[0B141f51f6: Pulling fs layer
[0Bc28826c5: Pulling fs layer
[0B1f737f36: Pulling fs layer
[0Bd7677c90: Pulling fs layer
[0Ba21039ee: Pulling fs layer
Digest: sha256:b86f20b15c6794b304c5f89d80ba0dceb4621a62178c5f0ebd56960a4c82b464   469 B/469 B MBB
Status: Downloaded newer image for elasticsearch:2.2.0
Creating docker_elk-elasticsearch_1
Pulling elk-logstash (logstash:2.2.2)...
2.2.2: Pulling from library/logstash

[0Bd7827f33: Already exists
[0B95caeb02: Already exists
[0Bd0fe50cc: Already exists
[0B1295bce9: Already exists
[4B95caeb02: Already exists
[5B95caeb02: Already exists
[0B44e1612b: Already exists
[0Bd9deb980: Already exists
[0Bdfa401d8: Pulling fs layer
[9B95caeb02: Pulling fs layer
[0B7de96b78: Pulling fs layer
[0Bf5ab4e6c: Pulling fs layer
[0B2acd23e4: Pulling fs layer
[0B4a20918d: Pulling fs layer
Digest: sha256:2b5e3e2f24152978a297c010745fc281438659f355972f93de148ee439f5195b   252 B/252 B MBB
Status: Downloaded newer image for logstash:2.2.2
Creating docker_elk-logstash_1
Pulling gatewayapp (jhipster/gatewayapp:latest)...
Pulling repository docker.io/jhipster/gatewayapp
[31mERROR[0m: Error: image jhipster/gatewayapp not found
PS D:\Projects\singsug\ms\docker>
```

**Comment by deepu105** [comment]
@pascalgrimaud why is the repo being pulled from `docker.io/jhipster/gatewayapp` shouldnt it be local. Sorry Im not very familar with how docker works so may be a lame question

**Comment by pascalgrimaud** [comment]
Before launching docker-compose you have to "containerize" every applications.
So in every sub projects, you have to : `./gradlew -Pprod bootRepackage -x test buildDocker`

**Comment by pascalgrimaud** [comment]
I suppose you are with gradle :smile: 
With maven, it's : `mvn package -Pprod docker:build`

**Comment by deepu105** [comment]
No im using maven here. I have did that and the war file is present in my target/docker folder

**Comment by deepu105** [comment]
This generator fails without the war files actually :) so I have built all the containers

**Comment by pascalgrimaud** [comment]
How docker works:
1) docker tries to find and start local image
2) if it doesn't find one, it will try to find it on docker hub, or another hub you can redefine

Once you containerize your applications with `mvn package -Pprod docker:build`, type `docker images` and try to find the image corresponding to your microservice/gateway application

**Comment by deepu105** [comment]
is there any connection to the warname and service name in the docker config?

**Comment by deepu105** [comment]
the generated docker-compose.yml looks like below. my war file is named `gateway-app-0.0.1-SNAPSHOT.war`  anyway im gonna try to build again from scratch

```
version: '2'
services:
    jhipster-registry:
        extends:
            file: registry.yml
            service: jhipster-registry
        volumes:
            - ./central-server-config:/central-config
    gateway-app:
        extends:
            file: D:\Projects\singsug\ms\gatewayApp/src/main/docker/app.dev.yml
            service: gatewayapp-dev-app
    msapp-1:
        extends:
            file: D:\Projects\singsug\ms\msapp1/src/main/docker/app.dev.yml
            service: msapp1-dev-app
    msapp-2:
        extends:
            file: D:\Projects\singsug\ms\msapp2/src/main/docker/app.dev.yml
            service: msapp2-dev-app

    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    jhipster-console:
        extends:
            file: elk.yml
            service: jhipster-console


```
