### ISSUE TITLE
generated ELK logstash container fails with error

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster-docker-compose#3]
when doing `docker-compose up -d` the elk_logstash_1 container fails with below error

```
Error: No config files found: /config-dir/logstash.conf
Can you make sure this path is a logstash config file?
You may be interested in the '--configtest' flag which you can
use to validate logstash's configuration before you choose
to restart a running system.
```

**Comment by wmarques** [comment]
Strange, I don't have this error.. It seems that logstash couldn't find the file `logstash.conf` located in `log-monitoring/log-config`.

**Comment by deepu105** [comment]
yes in the config I see below, shouldnt this be pointing to `og-monitoring/log-config/logstash.conf` instead of `/config-dir/logstash.conf`

@wmarques @cbornet @gmarziou @pascalgrimaud @PierreBesson any one have a quick hack or suggestion for this. I really wanted to demo the kibana dashoard tomorrow

```
elk-logstash:
        image: logstash:2.2.2
        volumes:
            - ./log-monitoring/log-config/:/config-dir
        command: logstash -f /config-dir/logstash.conf
        ports:
            - "5000:5000/udp"
```
